export const data = [
 
  
    {
        id:'1',
        sender:{
            id:'1',
            name:'Ren',
            img_url:require('./src/assets/images/profPics/5.png'),
        },
        is_private:true,
        reciever:{
            id:'680e7fc4-d135-4f35-83e0-8ef578926fe4',
            name:'Michel',
            img_url:require('./src/assets/images/profPics/6.png'),
        },
        update_history:[
            {
                content: "Lol,great Lets go out for some tonight?",
                updated_at:'2023-01-17T10:19:06.031Z',
            }
        ]
    },
    {
        id:'2',
        sender:{
            id:'680e7fc4-d135-4f35-83e0-8ef578926fe4',
            name:'Michel',
            img_url:require('./src/assets/images/profPics/6.png'),
        },
        is_private:true,
        reciever:{
            id:'1',
            name:'Ren',
            img_url:require('./src/assets/images/profPics/5.png'),
        },
        update_history:[
            {
                content: "Yeh bruh",
                updated_at:'2023-01-17T10:19:06.031Z',
            }
        ]
    },
    {
        id:'3',
        sender:{
            id:'1',
            name:'Ren',
            img_url:require('./src/assets/images/profPics/5.png'),
        },
        is_private:true,
        reciever:{
            id:'680e7fc4-d135-4f35-83e0-8ef578926fe4',
            name:'Michel',
            img_url:require('./src/assets/images/profPics/6.png'),
        },
        update_history:[
            {
                content: "You love Pizza?",
                updated_at:'2023-01-17T10:19:06.031Z',
            }
        ]
    },
    {
        id:'4',
        sender:{
            id:'1',
            name:'Ren',
            img_url:require('./src/assets/images/profPics/5.png'),
        },
        is_private:true,
        reciever:{
            id:'680e7fc4-d135-4f35-83e0-8ef578926fe4',
            name:'Michel',
            img_url:require('./src/assets/images/profPics/6.png'),
        },
        update_history:[
            {
                content: "You love Pizza?",
                updated_at:'2023-01-17T10:19:06.031Z',
            }
        ]
    },
    {
        id:'5',
        sender:{
            id:'680e7fc4-d135-4f35-83e0-8ef578926fe4',
            name:'Michel',
            img_url:require('./src/assets/images/profPics/6.png'),
        },
        is_private:true,
        reciever:{
            id:'1',
            name:'Ren',
            img_url:require('./src/assets/images/profPics/5.png'),
        },
        update_history:[
            {
                content: "Yeh bruh",
                updated_at:'2023-01-17T10:19:06.031Z',
            }
        ]
    },
    {
        id:'6',
        sender:{
            id:'680e7fc4-d135-4f35-83e0-8ef578926fe4',
            name:'Michel',
            img_url:require('./src/assets/images/profPics/6.png'),
        },
        is_private:true,
        reciever:{
            id:'1',
            name:'Ren',
            img_url:require('./src/assets/images/profPics/5.png'),
        },
        update_history:[
            {
                content: "Yeh bruh",
                updated_at:'2023-01-17T10:19:06.031Z',
            }
        ]
    },
    {
        id:'7',
        sender:{
            id:'680e7fc4-d135-4f35-83e0-8ef578926fe4',
            name:'Michel',
            img_url:require('./src/assets/images/profPics/6.png'),
        },
        is_private:true,
        reciever:{
            id:'1',
            name:'Ren',
            img_url:require('./src/assets/images/profPics/5.png'),
        },
        update_history:[
            {
                content: "Yeh bruh",
                updated_at:'2023-01-17T10:19:06.031Z',
            }
        ]
    },
    {
        id:'8',
        sender:{
            id:'680e7fc4-d135-4f35-83e0-8ef578926fe4',
            name:'Michel',
            img_url:require('./src/assets/images/profPics/6.png'),
        },
        is_private:true,
        reciever:{
            id:'1',
            name:'Ren',
            img_url:require('./src/assets/images/profPics/5.png'),
        },
        update_history:[
            {
                content: "Yeh bruh",
                updated_at:'2023-01-17T10:19:06.031Z',
            }
        ]
    },
    {
        id:'9',
        sender:{
            id:'680e7fc4-d135-4f35-83e0-8ef578926fe4',
            name:'Michel',
            img_url:require('./src/assets/images/profPics/6.png'),
        },
        is_private:true,
        reciever:{
            id:'1',
            name:'Ren',
            img_url:require('./src/assets/images/profPics/5.png'),
        },
        update_history:[
            {
                content: "Yeh bruh",
                updated_at:'2023-01-17T10:19:06.031Z',
            }
        ]
    },
    {
        id:'10',
        sender:{
            id:'680e7fc4-d135-4f35-83e0-8ef578926fe4',
            name:'Michel',
            img_url:require('./src/assets/images/profPics/6.png'),
        },
        is_private:true,
        reciever:{
            id:'1',
            name:'Ren',
            img_url:require('./src/assets/images/profPics/5.png'),
        },
        update_history:[
            {
                content: "Yeh bruh",
                updated_at:'2023-01-17T10:19:06.031Z',
            }
        ]
    },
];
